### ISSUE TITLE
nrpe-external-master.available isn't available on upgrade-charm (or non relation-* hooks)

### ISSUE THREAD

**Issue by hloeung** [cmars/nrpe-external-master-interface#12]
Hi,

nrpe-external-master.available isn't available on upgrade-charm and therefore bits to reconfigure nagios aren't firing. Example of a charm we've seen this:

https://git.launchpad.net/content-cache-charm/tree/reactive/content_cache.py

`@reactive.hook('upgrade-charm')
def upgrade_charm():
    reactive.clear_flag('nagios-nrpe.configured')
`

`@reactive.when('nrpe-external-master.available')
@reactive.when_not('nagios-nrpe.configured')
def configure_nagios():
    status.maintenance('setting up NRPE checks')
`

**Comment by cmars** [comment]
If I'm understanding correctly, removing this line would address the issue for you? https://github.com/cmars/nrpe-external-master-interface/blob/master/provides.py#L92

**Comment by hloeung** [comment]
Per IRC, I think that might resolve it but I have no experience with writing charm layers and interfaces.

Maybe @stub42 can add some input here?
