### ISSUE TITLE
May fire before subordinate is ready

### ISSUE THREAD

**Issue by stub42** [cmars/nrpe-external-master-interface#3]
The nrpe-external-master.available state gets set as soon as the nrpe-external-master relation is joined. At this point, the nrpe subordinate may not have actually been installed. Operations such as installing custom checks may fail, as the nagios user and nagios specific paths do not exist.

**Comment by cmars** [comment]
I find this behavior surprising. Is this limited to relating with subordinates, or do charms need to be able to handle relation hooks before both services have installed _in general_? I've never found that to be the case, even with the nrpe subordinate, and I'm using the new native bundle deployment support in Juju 2.0 that add relations immediately after deploying everything, when nothing is installed.

I've only deployed this on Juju 1.25 and newer. Maybe older Juju versions had different behavior?

**Comment by cmars** [comment]
@stub42 What version of Juju had this issue?

**Comment by stub42** [comment]
I thought it was all versions of Juju, but I haven't been able to confirm my hypothesis. I guess something else went wrong, like the nrpe install hook failing silently.
